// Code generated by protoc-gen-go.
// source: sessions.proto
// DO NOT EDIT!

/*
Package grps is a generated protocol buffer package.

It is generated from these files:
	sessions.proto

It has these top-level messages:
	SessionRequest
	SessionReply
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's credentials.
type SessionRequest struct {
	Login string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Pass  string `protobuf:"bytes,2,opt,name=pass" json:"pass,omitempty"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the token
type SessionReply struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *SessionReply) Reset()                    { *m = SessionReply{} }
func (m *SessionReply) String() string            { return proto.CompactTextString(m) }
func (*SessionReply) ProtoMessage()               {}
func (*SessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SessionRequest)(nil), "grps.SessionRequest")
	proto.RegisterType((*SessionReply)(nil), "grps.SessionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Session service

type SessionClient interface {
	// Sends a greeting
	Create(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionReply, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) Create(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	out := new(SessionReply)
	err := grpc.Invoke(ctx, "/grps.Session/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	// Sends a greeting
	Create(context.Context, *SessionRequest) (*SessionReply, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grps.Session/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).Create(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grps.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Session_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x28,
	0x56, 0xb2, 0xe2, 0xe2, 0x0b, 0x86, 0x88, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89,
	0x70, 0xb1, 0xe6, 0xe4, 0xa7, 0x67, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38,
	0x42, 0x42, 0x5c, 0x2c, 0x05, 0x89, 0xc5, 0xc5, 0x12, 0x4c, 0x60, 0x41, 0x30, 0x5b, 0x49, 0x85,
	0x8b, 0x07, 0xae, 0xb7, 0x20, 0xa7, 0x12, 0xa4, 0xb3, 0x24, 0x3f, 0x3b, 0x15, 0xae, 0x13, 0xcc,
	0x31, 0xb2, 0xe7, 0x62, 0x87, 0xaa, 0x12, 0x32, 0xe1, 0x62, 0x73, 0x2e, 0x4a, 0x4d, 0x2c, 0x49,
	0x15, 0x12, 0xd1, 0x03, 0xd9, 0xae, 0x87, 0x6a, 0xb5, 0x94, 0x10, 0x9a, 0x28, 0xd0, 0x50, 0x25,
	0x86, 0x24, 0x36, 0xb0, 0x7b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xde, 0x3c, 0xf8,
	0xc1, 0x00, 0x00, 0x00,
}
